// Package grpc provides proto types for IdentityCloud service
// This file contains manually-defined types that would typically be generated by protoc
package grpc

// EntityType classification for UnifiedID
type EntityType int32

const (
	EntityType_ENTITY_TYPE_UNSPECIFIED  EntityType = 0
	EntityType_ENTITY_TYPE_HUMAN        EntityType = 1
	EntityType_ENTITY_TYPE_AGENT        EntityType = 2
	EntityType_ENTITY_TYPE_ORGANIZATION EntityType = 3
)

// UnifiedID represents a W3C DID-based identity
type UnifiedID struct {
	Did        string     `json:"did"`
	EntityType EntityType `json:"entity_type"`
	ParentDid  *string    `json:"parent_did,omitempty"`
	CreatedAt  int64      `json:"created_at"`
	PublicKey  []byte     `json:"public_key"`
}

// TrustComponents holds the breakdown of trust score components
type TrustComponents struct {
	VerificationScore uint32 `json:"verification_score"`
	DisputePenalty    uint32 `json:"dispute_penalty"`
	SlaScore          uint32 `json:"sla_score"`
	NetworkScore      uint32 `json:"network_score"`
}

// TrustScore represents an entity's trust score with full breakdown
type TrustScore struct {
	Score            uint32           `json:"score"`
	Components       *TrustComponents `json:"components"`
	UpdatedAt        int64            `json:"updated_at"`
	VerifiedOutcomes uint64           `json:"verified_outcomes"`
	DisputeRate      float64          `json:"dispute_rate"`
	Version          uint64           `json:"version"`
}

// HcWallet represents a Harness Credits wallet
type HcWallet struct {
	OwnerDid  string `json:"owner_did"`
	Available string `json:"available"`
	Locked    string `json:"locked"`
	ExpiresAt int64  `json:"expires_at"`
	Version   uint64 `json:"version"`
	UpdatedAt int64  `json:"updated_at"`
}

// CreateUnifiedIDRequest is the request for CreateUnifiedID
type CreateUnifiedIDRequest struct {
	EntityType EntityType `json:"entity_type"`
	ParentDid  *string    `json:"parent_did,omitempty"`
	PublicKey  []byte     `json:"public_key"`
	Domain     *string    `json:"domain,omitempty"`
}

// CreateUnifiedIDResponse is the response for CreateUnifiedID
type CreateUnifiedIDResponse struct {
	UnifiedId  *UnifiedID  `json:"unified_id"`
	TrustScore *TrustScore `json:"trust_score"`
	Wallet     *HcWallet   `json:"wallet"`
}

// GetUnifiedIDRequest is the request for GetUnifiedID
type GetUnifiedIDRequest struct {
	Did string `json:"did"`
}

// GetUnifiedIDResponse is the response for GetUnifiedID
type GetUnifiedIDResponse struct {
	UnifiedId *UnifiedID `json:"unified_id"`
}

// ResolveLineageRequest is the request for ResolveLineage
type ResolveLineageRequest struct {
	Did      string `json:"did"`
	MaxDepth uint32 `json:"max_depth"`
}

// ResolveLineageResponse is the response for ResolveLineage
type ResolveLineageResponse struct {
	Lineage          []*UnifiedID `json:"lineage"`
	TrustInheritance []float64    `json:"trust_inheritance"`
}

// GetTrustScoreRequest is the request for GetTrustScore
type GetTrustScoreRequest struct {
	Did string `json:"did"`
}

// GetTrustScoreResponse is the response for GetTrustScore
type GetTrustScoreResponse struct {
	TrustScore *TrustScore `json:"trust_score"`
}

// VerificationUpdate represents a verification outcome update
type VerificationUpdate struct {
	Success bool `json:"success"`
}

// DisputeUpdate represents a dispute update
type DisputeUpdate struct {
	DisputeOccurred bool `json:"dispute_occurred"`
	DisputeWon      bool `json:"dispute_won"`
}

// UpdateTrustScoreRequest is the request for UpdateTrustScore
type UpdateTrustScoreRequest struct {
	Did                string              `json:"did"`
	VerificationUpdate *VerificationUpdate `json:"verification_update,omitempty"`
	DisputeUpdate      *DisputeUpdate      `json:"dispute_update,omitempty"`
	SlaCompliance      *float64            `json:"sla_compliance,omitempty"`
	NetworkReputation  *float64            `json:"network_reputation,omitempty"`
	ExpectedVersion    uint64              `json:"expected_version"`
}

// UpdateTrustScoreResponse is the response for UpdateTrustScore
type UpdateTrustScoreResponse struct {
	TrustScore *TrustScore `json:"trust_score"`
}

// GetWalletRequest is the request for GetWallet
type GetWalletRequest struct {
	Did string `json:"did"`
}

// GetWalletResponse is the response for GetWallet
type GetWalletResponse struct {
	Wallet *HcWallet `json:"wallet"`
}

// CreditWalletRequest is the request for CreditWallet
type CreditWalletRequest struct {
	Did         string  `json:"did"`
	Amount      string  `json:"amount"`
	Reason      string  `json:"reason"`
	ReferenceId *string `json:"reference_id,omitempty"`
}

// CreditWalletResponse is the response for CreditWallet
type CreditWalletResponse struct {
	Wallet *HcWallet `json:"wallet"`
}

// DebitWalletRequest is the request for DebitWallet
type DebitWalletRequest struct {
	Did             string  `json:"did"`
	Amount          string  `json:"amount"`
	Reason          string  `json:"reason"`
	ReferenceId     *string `json:"reference_id,omitempty"`
	ExpectedVersion uint64  `json:"expected_version"`
}

// DebitWalletResponse is the response for DebitWallet
type DebitWalletResponse struct {
	Wallet *HcWallet `json:"wallet"`
}

// LockWalletRequest is the request for LockWallet
type LockWalletRequest struct {
	Did             string `json:"did"`
	Amount          string `json:"amount"`
	EscrowId        string `json:"escrow_id"`
	ExpectedVersion uint64 `json:"expected_version"`
}

// LockWalletResponse is the response for LockWallet
type LockWalletResponse struct {
	Wallet *HcWallet `json:"wallet"`
}

// ReleaseWalletRequest is the request for ReleaseWallet
type ReleaseWalletRequest struct {
	Did             string  `json:"did"`
	Amount          string  `json:"amount"`
	EscrowId        string  `json:"escrow_id"`
	TargetDid       *string `json:"target_did,omitempty"`
	ExpectedVersion uint64  `json:"expected_version"`
}

// ReleaseWalletResponse is the response for ReleaseWallet
type ReleaseWalletResponse struct {
	Wallet *HcWallet `json:"wallet"`
}

// VerifySignatureRequest is the request for VerifySignature
type VerifySignatureRequest struct {
	Did       string `json:"did"`
	Message   []byte `json:"message"`
	Signature []byte `json:"signature"`
}

// VerifySignatureResponse is the response for VerifySignature
type VerifySignatureResponse struct {
	Valid bool `json:"valid"`
}

// UnimplementedIdentityServiceServer is a placeholder for unimplemented methods
type UnimplementedIdentityServiceServer struct{}
